/**
 * Conformidad con Target v1.5.1 — entradas de policy CONGELADAS.
 *
 * Extraccion MECANICA de las 85 corridas de B2.4.1 que quedaron congeladas al
 * cerrar la investigacion: la re-ejecucion completa de development mas el
 * Holdout. Para cada corrida se toman
 *
 *     03_objective_analysis.analysis.requirements[0]  target y evaluabilidad
 *     05_unified_contextual_reasoning[0]              los juicios del razonador
 *     07_epistemic_policy[0]                          preGuardState y finalState
 *
 * SOLO TOKENS. No se copia una sola frase del corpus de investigacion: ni texto
 * de Requirement, ni proposiciones, ni citas, ni rationales. La policy no los
 * lee, asi que no hacen falta para replicarla — y un fixture del producto no es
 * lugar para material de otro corpus.
 *
 * NO SE IMPORTA NADA DE `experiments/`. Estos son datos, extraidos una vez y
 * congelados aca; el runtime productivo no toca los archivos de investigacion.
 *
 * Las corridas repetidas del mismo caso se conservan a proposito: son las que
 * el candidato realmente produjo, y el conteo es parte de la evidencia.
 */

/** Una corrida congelada, reducida a lo que la policy determinista consume. */
export interface FrozenPolicyConformanceRow {
  readonly run: string;
  readonly epistemicTarget: string;
  readonly formativeEvidenceCapable: boolean;
  readonly semanticUnresolved: boolean;
  readonly compositionUnresolved: boolean;
  readonly fullClaimStatus: string;
  readonly observabilityStatus: string;
  readonly weakerSearchStatus: string;
  readonly continuityStatus: string | null;
  readonly materialUsefulness: string | null;
  readonly hardFactualFailure: boolean;
  /** Lo que Target v1.5.1 produjo sin guards duros. */
  readonly preGuardState: string;
  /** Lo que Target v1.5.1 produjo. */
  readonly finalState: string;
}

export const FROZEN_B241_POLICY_CONFORMANCE: readonly FrozenPolicyConformanceRow[] = [
  { run: 'case_01_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_01_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_01_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_01_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_01_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_03_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_03_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_03_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_03_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_03_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_05_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_05_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_05_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_05_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_05_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_06_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_06_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_06_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_06_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_06_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_07_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_07_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_07_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_07_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_07_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_08_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_08_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_08_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_08_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_08_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_09_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_09_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_09_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_09_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_09_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_11_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_11_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_11_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_11_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_11_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_12_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_12_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_12_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_12_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_12_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_13_r1', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'UNRESOLVED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_13_r2', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'UNRESOLVED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_13_r3', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'UNRESOLVED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_13_r4', epistemicTarget: 'INDIVIDUAL_ACHIEVEMENT', formativeEvidenceCapable: false, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_13_r5', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'UNRESOLVED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_15_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'MATERIAL_GAP', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'ABSTAIN', finalState: 'ABSTAIN' },
  { run: 'case_15_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'MATERIAL_GAP', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'ABSTAIN', finalState: 'ABSTAIN' },
  { run: 'case_15_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'MATERIAL_GAP', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'ABSTAIN', finalState: 'ABSTAIN' },
  { run: 'case_15_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'MATERIAL_GAP', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'ABSTAIN', finalState: 'ABSTAIN' },
  { run: 'case_15_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'MATERIAL_GAP', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'ABSTAIN', finalState: 'ABSTAIN' },
  { run: 'case_02_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_02_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_02_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_02_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_02_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_04_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_04_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_04_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_04_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_04_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_10_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_10_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_10_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_10_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_10_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_14_r1', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: true, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_14_r2', epistemicTarget: 'UNRESOLVED', formativeEvidenceCapable: false, semanticUnresolved: true, compositionUnresolved: true, fullClaimStatus: 'UNRESOLVED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'UNRESOLVED', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_14_r3', epistemicTarget: 'INDIVIDUAL_ACHIEVEMENT', formativeEvidenceCapable: false, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_14_r4', epistemicTarget: 'INDIVIDUAL_ACHIEVEMENT', formativeEvidenceCapable: false, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_14_r5', epistemicTarget: 'INDIVIDUAL_ACHIEVEMENT', formativeEvidenceCapable: false, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'NOT_ASSESSABLE', finalState: 'NOT_ASSESSABLE' },
  { run: 'case_16_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_16_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_16_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_16_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_16_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'NONE', continuityStatus: null, materialUsefulness: null, hardFactualFailure: false, preGuardState: 'SUPPORTED', finalState: 'SUPPORTED' },
  { run: 'case_17_r1', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'YES', materialUsefulness: 'YES', hardFactualFailure: false, preGuardState: 'PARTIALLY_SUPPORTED', finalState: 'PARTIALLY_SUPPORTED' },
  { run: 'case_17_r2', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_17_r3', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_17_r4', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' },
  { run: 'case_17_r5', epistemicTarget: 'FORMATIVE_EVIDENCE', formativeEvidenceCapable: true, semanticUnresolved: false, compositionUnresolved: false, fullClaimStatus: 'NOT_REACHED', observabilityStatus: 'SUFFICIENT', weakerSearchStatus: 'FOUND', continuityStatus: 'NO', materialUsefulness: 'NOT_EVALUATED', hardFactualFailure: false, preGuardState: 'INSUFFICIENT_EVIDENCE', finalState: 'INSUFFICIENT_EVIDENCE' }
];
